dist: trusty
sudo: required
language: node_js
node_js:
  - "node"
cache:
  directories:
    - "node_modules"
addons:
  sonarcloud:
    organization: "dylanaubrey-github"
    token:
      secure: $SONAR_TOKEN
    github_token:
      secure: $SONAR_PR_ANALYSIS_TOKEN
script:
  - npm test
  - sonar-scanner
  - codecov
  - npm run compile
deploy:
  provider: npm
  email: "dylanaubrey@gmail.com"
  api_key: $NPM_AUTH_TOKEN
  skip_cleanup: true
  on:
    branch: master
